language: java
sudo: false
matrix:
  include:
    - language: nodejs
      node_js:
        - "node"
        - "lts/*"
        - "8"

      addons:
      apt:
        packages:
          - google-chrome-stable

      before_script:
        - cd client
        - yarn global add @angular/cli@6.0.3
        - yarn global add karma
        - yarn install
      script:
        - ng test --watch=false --browsers=ChromeHeadlessNoSandbox
        - ng build --prod --build-optimizer

    - language: java
      jdk: oraclejdk8
      before_script:
        - (cd server; gradle assemble)
      script:
        - (cd server; gradle check)