name: moneyControl
description: moneyControl frontend
dependencies:
  angular: "1.0.0"
  web_components: ">=0.8.0 <0.9.0"
  browser: any
  http_server: ">=0.9.3 <0.10.0"
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"
transformers:
- angular:
    html_files:
      - lib/component/celledit_component.html
      - lib/component/numberedit_component.html
      - lib/component/datebar_component.html
      - lib/component/navbar_component.html
      - lib/component/operations_component.html