name: Continuous Integration

on: [push]

jobs:
  build-front:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      working-directory: front
      run: |
        npm install
    - name: unit test
      working-directory: front
      run: |
        npm run test:unit
      env:
        CI: true

  build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Build with Gradle
        working-directory: back
        "run: ./gradlew build  --scan"
      env:
        CI: true

