name: Continuous Integration

on: [push]

jobs:
  build-front:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: NPM install
      working-directory: front
      run: |
        npm install
    - name: Unit test
      working-directory: front
      run: |
        npm run test:unit
    - name: Build
      working-directory: front
      run: |
        npm run build
      env:
        CI: true

  build-back:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.7
    - name: Gradle build
      working-directory: back
      run: ./gradlew build --scan
      env:
        CI: true

  build-new-back:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.7
    - name: Gradle build
      working-directory: newback
      run: ./gradlew build --scan
      env:
        CI: true

